import { Flex, Center, Text, Container } from "@chakra-ui/react";
import { Box } from "@chakra-ui/layout";
import type { NextPage } from "next";
import Head from "next/head";

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>NA | ABOUT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Text>ABOUT</Text>
      </Box>
    </>
  );
};

export default About;
