import { SimpleGrid, GridItem, useMediaQuery, VStack, Flex } from "@chakra-ui/react";
import { Box, type BoxProps } from "@chakra-ui/layout";
import Image from "next/image";
import { motion } from "framer-motion";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import illustrations from "../public/assets/images";
import Section from "../components/Section";
import Illustration from "../components/illustration"
import Home from "../components/Home";
import UI from "../components/UI";
import Patterns from "../components/Patterns";
import Contact from "../components/Contact";

export const MotionBox = motion<BoxProps>(Box);

const Index: NextPage = () => {
  const [selectedPic, setSelectedPic] = useState(0);
  const [isMD] = useMediaQuery(["(min-width: 768px)"]);

  return (
    <>
      <Head>
        <title>NA | HOME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/assets/na.png" />
      </Head>
      <VStack spacing={0} w='100vw'>
        <Section id='home' bgColor="white"><p><Home /></p></Section>
        <Section id='ui' bgColor="#008080"><p><UI /></p></Section>
        <Section id='illustration' bgColor="#EA4141"><Illustration /></Section>
        <Section id='patterns' bgColor="#FFB4D8"><p><Patterns /></p></Section>
        <Section id='contact' bgColor="#FE993B"><p><Contact /></p></Section>
      </VStack>
    </>
  );
};

export default Index;
