import { Flex, Heading, Spinner, Text } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <Flex height="100vh" justifyContent="center" alignItems="center" flexDirection="column">
      <Head>
        <title>Nadia Ramirez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading>Nadia Ramirez</Heading>
      <Flex mt="10px">
        <Text color="#ccc" mr="10px">Coming soon</Text>
        <Spinner color="red.500"/>
      </Flex>
    </Flex>
  )
}

export default Home
