import { Flex, Center, Text, Container } from "@chakra-ui/react";
import { Box } from "@chakra-ui/layout";
import type { NextPage } from "next";
import Head from "next/head";

const Patterns: NextPage = () => {
  return (
    <>
      <Head>
        <title>NA | PATTERNS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Text>PATTERNS</Text>
      </Box>
    </>
  );
};

export default Patterns;
